service: products-service
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  stage: dev
  profile: default
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    NODE_ENV: dev
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000
    PRODUCTS_TABLE_NAME: ${env:PRODUCTS_TABLE_NAME}
    STOCKS_TABLE_NAME: ${env:STOCKS_TABLE_NAME}
  iam:
    role: ${file(./sls/iam.yml):role}

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude: [ "aws-sdk" ]
    target: "node16"
    platform: "node"
    concurrency: 10

functions:
  - ${file(./sls/functions.yml)}
